# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql2
  encoding: utf8
  database: blog_development
  username: root
  host: localhost
  password:
production:
  adapter: mysql2
  encoding: utf8
  database: blog_production
  username: root
  host: localhost
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: blog_test
  username: root
  host: localhost
  password:
